apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opencost-exporter.fullname" . }}
  labels:
    {{- include "opencost-exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "opencost-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "opencost-exporter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "opencost-exporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          args:
            - --bucket
            - {{ .Values.aws.bucket }}
            - --report
            - {{ .Values.aws.report }}
          env:
            - name: AWS_REGION
              value: {{ .Values.aws.region }}
            - name: AWS_SHARED_CREDENTIALS_FILE
              value: /etc/aws/credentials
          ports:
            - name: http-metrics
              containerPort: 9100
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http-metrics
          readinessProbe:
            httpGet:
              path: /
              port: http-metrics
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: aws-secrets
              mountPath: /etc/aws
            - name: data
              mountPath: /var/lib/opencost-exporter
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: aws-secrets
          secret:
            secretName: {{ include "opencost-exporter.fullname" . }}-aws
            defaultMode: 111
        - name: data
          emptyDir: {}
