apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opencost-exporter.fullname" . }}-aws
  labels:
    {{- include "opencost-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  credentials: |
    [default]
    aws_access_key_id={{ .Values.aws.access_key_id }}
    aws_secret_access_key={{ .Values.aws.secret_access_key }}
